"""sync db

Revision ID: 521608e36969
Revises: 07555b37e5fe
Create Date: 2026-03-24 17:39:05.203806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521608e36969'
down_revision: Union[str, None] = '07555b37e5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles") as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.create_foreign_key(
            "fk_articles_author",
            "users",
            ["author_id"],
            ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###
